name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  wait-and-merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Wait for 2 hours
      run: |
        echo "等待2小时后自动合并PR..."
        sleep 7200  # 2小时 = 7200秒
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
    
    - name: Build project
      run: |
        npm run docs:build
    
    - name: Check if PR can be merged
      id: check-merge
      run: |
        # 检查PR是否可以通过自动化检查
        if gh pr view --json mergeable --jq '.mergeable' | grep -q "MERGEABLE"; then
          echo "can_merge=true" >> $GITHUB_OUTPUT
        else
          echo "can_merge=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Merge PR
      if: steps.check-merge.outputs.can_merge == 'true'
      run: |
        echo "正在合并PR..."
        gh pr merge --merge --auto
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Comment on PR
      if: steps.check-merge.outputs.can_merge == 'true'
      run: |
        echo "添加合并评论..."
        gh pr comment --body "✅ PR已自动合并（等待2小时后）"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Comment on PR (cannot merge)
      if: steps.check-merge.outputs.can_merge == 'false'
      run: |
        echo "添加无法合并评论..."
        gh pr comment --body "❌ PR无法自动合并，请检查冲突或失败的工作流"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}